### ISSUE TITLE
Music player

### ISSUE THREAD

**Issue by dhelms1** [ChicoState/sound-space#64]
Get trending page song list clickable so user can stream song.

Eventually will want to reroute them to music page and start playing song there (@snowmang1)

**Comment by snowmang1** [comment]
Hey how does one display an image as a returnable widget?
I think it needs to be a stateful widget but I can convert if neccisary.

**Comment by snowmang1** [comment]
<img width="946" alt="Screen Shot 2022-04-20 at 12 39 20 PM" src="https://user-images.githubusercontent.com/31263887/164309696-d40b4513-2837-4d8d-a452-a1c3960399a0.png">
this should be the lines we need to change to make the yt player headless

**Comment by dhelms1** [comment]
is it the network image that is displaying the actual video?

**Comment by dhelms1** [comment]
I think we could also put the actual video inside a widget and minimize it, so technically it would be playing but you wouldn't see it... And then have the controls below that hidden widget as our "music" controls. Similar to this: https://www.youtube.com/watch?v=v1pBKuK3-nY

**Comment by snowmang1** [comment]
this is something prof suggested in lab on wednessday. the only problem was I dont know UI so I was going to clear that ifea with you.

**Comment by dhelms1** [comment]
Just wanted to throw this in here as a possible idea: if we can't hide the video and get it to autoplay or function with only the playback buttons then we could just play the original video (smallish size) where the current art list is on the music page. Then have the art list and music below the search button, and once the person selects the song it loads the video and switches the music list for the art tiles (could do this with the Visibility() widget), then have a button to "view music list" that swaps the art tiles back to the music list

(or possibly do this as two columns with video on left and search + music/art on the right)

**Comment by dhelms1** [comment]
Going to close this since we technically have out music player working along with the visuals page.
