### ISSUE TITLE
More robust image upload/rendering

### ISSUE THREAD

**Issue by ornorth** [ChicoState/sound-space#77]
@snowmang1 I could do with a sanity check on this. Am I barking up the wrong tree?

So we're looking to get an image from a URL, something like https://imgur.com/gallery/9hwj5B1, right? Well I've been looking around and, basically, I don't think you can. There are plenty of ways to get/display/store an image from a URI like https://i.imgur.com/sCpuYbQ.png - which is what we've been doing - but if all you have is the URL then I think the only way is to scrape the site's HTML for a URI.

We could also try to let the users upload images from their own devices, using something like https://pub.dev/packages/image_picker_for_web. It looks like it would be a nightmare to implement, but I could try...

What do you think? There's a web scraper package for Dart, so I could do that without too much difficulty if that's the route we want to go. This method also has the advantage of being expandable; I could add scraper functionality for one website at a time

**Comment by snowmang1** [comment]
no the user can be asked to upload a uri and that can then be rendered. web scraping will add uneeded complexity and headaches that we simply do not need.

**Comment by snowmang1** [comment]
sorry this took so long i have been working.
