### ISSUE TITLE
Music Filtering

### ISSUE THREAD

**Issue by dhelms1** [ChicoState/sound-space#79]
Need to figure out how to filter the music list being created by the firebase snapshot when user enters text in search bar - I linked a quick video that I used to set it up, but they filter from a hard coded list so I wasn't sure how to implement with firebase.

**Comment by dhelms1** [comment]
If we can generate a list from the firebase instance I can use that for filtering, but not sure how to do this.

**Comment by snowmang1** [comment]
a list of what? Strings, objects?

**Comment by dhelms1** [comment]
Yeah basically what were using for the ListView.builder if we could take the snapshot and convert it to a list of strings or we could append each song into a list and use that to update the search bar (There's a video that shows how to filter with a list just not a firebase instance - I'll play around with this possibly tomorrow during lab)

**Comment by ornorth** [comment]
I was working on this today. I tried a couple methods, but Firebase doesn't seem to want to play nice with the listview. I'll keep working on it this week
