### ISSUE TITLE
Database prep for presentation

### ISSUE THREAD

**Issue by dhelms1** [ChicoState/sound-space#91]
- Clean out the database of the mp3 urls and images that don't load (I think there are 2 of them).
- We should prep some sets of art/videos/music to use for displaying the functionality of the website (a few songs, with associated pictures, and some videos).

**Comment by snowmang1** [comment]
This is being done in #107.

**Comment by dhelms1** [comment]
Upload a handful of songs, 2 of which will be used during presentation -> they have 7-8 associated images/videos that show up correctly. Closing this as it is ready
